# Generated by Django 3.0.1 on 2020-03-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='datetime',
            new_name='timestamp',
        ),
    ]
